### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by etoledo1** [dkovalenko420/PersonalProject#2]
First of all, I really like your website design and how clean it is. There is almost no text and the index page seems really professional. I liked the background video and how you maintained the same colors and fonts for every page. I could not find big errors in your code so my technical suggestions are related to small things:
1. At some points in your code you are adding px even when it is a 0, for example: left: 0px; → in this cases it should be: left: 0;
2. It might have been a conscious decision since this is the standard code in VS, but all your pages have <html> instead of <html lang="en"> → You should consider adding the language to the html tag to declare it.
3. For the <button> tag with the <a> tag, unfortunately the way you wrote is not accessible. I found a programmer who mentioned this: _“Tab stops (e.g. links) should not contain tab stops (e.g. buttons) because Assistive Tech (screen readers etc.) do not know how to present them to the user. Ask yourself: Which one gets keyboard focus via tabbing? Which one is supposed to handle the click event? So, besides failing the HTML validator, you'll also violate WCAG, which can have legal consequences”_. Therefore, I believe it might be better to style the <a> tag and make it look like a button 🙂
4. Finally, once again it might have been a conscious decision but there is a white margin in your index page that - to me, personally - does not really match your design since everything is mostly black and then the white margin breaks the sense of continuity. This might be completely personal based on my preferences.
5. For the feedback form, I noticed that the user is able to mark all options “Great -- Awesome -- Good”, and this is definitely not what you want. You can check here https://www.w3schools.com/html/html_forms.asp to see if that helps, and maybe something like that:

```
<form>
  <input type="radio" id="great" name="rating" value="Great">
  <label for="great">HTML</label><br>
  <input type="radio" id="awesome" name="rating" value="Awesome">
  <label for="awesome">CSS</label><br>
  <input type="radio" id="good" name="rating" value="Good">
  <label for="good">Good</label>
</form> 
```

Now, content-wise, as I said I liked the clean design and minimalistic approach, but I also think you should add some text to explain a little more about your project overall. For example, in the index page you could add just a little bit of text in animation mode explaining something about it just to make sure that the user is aware of what to expect. Other than that, I don't really have other content suggestions except for one small detail. In the feedback form, it is usually better to choose an order when ranking, for example terrible -- neutral -- good, or good -- neutral -- terrible. In your “What do you think of the music?” question the order is broken because the choices are “Great -- Awesome -- Good”, and this is not really helpful for you to understand the user’s feedback. Some suggestions:
1. “In a rank from 1 to 10, how much would you recommend/share this music to your friends?” 
2. “In a rank from 1 to 10, how much did you like/enjoy this music?” (I like rankings because they are very easy to measure)
3. “What do you think of the music?” Bad -- Neutral -- Great 
4. “What do you think of the music?” Good -- Great -- Awesome **(I do not recommend this one because there is no "bad" rating and you can't really know if the user liked your music or not)**

**Comment by dkovalenko420** [comment]
Thank you very much for such detailed feedback, it helped me a lot when redesigning the website! However, I have some comments regarding it. 

The feedback form was designed to grade the website and not the music itself. After this project is finished, this page will be removed completely. This is why I am not planning to ask visitors how good my music is. Regardless, I really appreciate the effort you put into redesigning the feedback form in your content suggestions. 

Also, your technical suggestions were on-point! I was able to implement most of them successfully. Furthermore, the website now works on mobile, which I think was a crucial iteration. Most people will be visiting the website from the link in my Instagram bio on their phones, so it was extremely important to add that technical feature.
